# 1. Cloud Database Connection
spring.datasource.url=jdbc:mysql://mysql-17fc9a9-kanugulacharan-c3c2.d.aivencloud.com:17685/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
server.port=8010
# 2. UPDATED Hibernate Settings
# Change 'MySQL8Dialect' to just 'MySQLDialect'
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Schema Management
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true