spring.application.name=s-book-backend
server.port=8010

# Local H2 Database (No internet needed)
spring.datasource.url=jdbc:h2:mem:sbookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
# Enable H2 Console so you can see your tables in the browser
spring.h2.console.enabled=true
# Change 'update' to 'create-drop' for one run to reset the tables
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
